### ISSUE TITLE
This should work

### ISSUE THREAD

**Issue by vgabaj** [RimacTechnology/style-guide#19]
```css
/* stylelint-disable-next-line media-feature-range-notation -- can't be satisfied */
@media (max-width: var(--responsive-breakpoint-small)) { 
    .groupRow {
        flex-direction: column;
        row-gap: 20px;
    }
}

```
